title: "Sneha Kattepura Chandrashekar"
author: "Sneha Kattepura Chandrashekar"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  #- {file: "index.html", title: "Home" }
  - {file: "sneha_resume.pdf", title: "Resume"}
 # - {file: "README.md", title: "About me", icon: address-card }
  - {file: "", title: "Projects"}
  - {file: "", title: "Contact"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:snehakchandrashekar@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/snehakchandrashekar"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
